<?php

return [

    'identity_fields' => [
        'id' => 'No.',
        'title' => 'Title',
        'proj_title' => 'Project Title',
        'prog_title' => 'Title of Research Program/Project/Work',
        'program' => 'Program Title',
        'pub_title' => 'Title of Publication',
        'article_title' => 'Article Title',
        'paper_title' => 'Title of Paper Presented',
        'patent_title' => 'Title of Patent',
        'output_title' => 'Title of Output',
    ],

    'people_fields' => [
        'proj_lead' => 'Project Leader (SN, FN MI.)',
        'proj_author' => 'Project Leader (SN, FN, MI)',
        'proj_staff' => 'Project Staff (SN, FN MI.)',
        'publication_author' => 'Name of Author and Co-Authors',
        'collaborators' => 'Collaborators',
        'name_editor' => 'Name of Editor/s',
        'name_inventor' => 'Name of Inventor(s)',
        'name_applicant' => 'Name of Applicant/Owner(s)',
        'name_of_holder' => 'Name of Holder',
        'name_organizer' => 'Name of Organizer',
        'partner_stakeholder' => 'Name of Partner Stakeholder',
    ],

    'organization_fields' => [
        'delivery_unit' => 'Delivery Unit',
        'contributing_unit' => 'Contributing/Implementing Unit',
        'implementing_unit' => 'Implementing Unit',
        'fund_source' => 'Fund Source',
        'fund_agency' => 'Funding Agency',
        'fund_type' => 'Funding Type',
        'type_category' => 'Type',
        'partnership_type' => 'Type of Extension Activities under Partnership',
        'department' => 'Dept/ Ins.',
    ],

    'date_fields' => [
        'start_date' => 'Start Date (DD/MM/YYYY)',
        'end_date' => 'End Date (DD/MM/YYYY)',
        'date_submitted' => 'Date Submitted (DD/MM/YYYY)',
        'date_published' => 'Date Published or Accepted for Publication (DD/MM/YYYY)',
        'date_awarded' => 'Date',
        'conf_start_date' => 'Conference Start Date (DD/MM/YYYY)',
        'conf_end_date' => 'Conference End Date (DD/MM/YYYY)',
        'date_presentation' => 'Date of Presentation (DD/MM/YYYY)',
        'event_start_date' => 'Event Start Date (DD/MM/YYYY)',
        'event_end_date' => 'Event End Date (DD/MM/YYYY)',
        'date_output' => 'Date the Output was first shown or released to the public (DD/MM/YYYY)',
        'Agreement_start_date' => 'Partnership Agreement Effectivity Start Date (DD/MM/YYYY)',
        'Agreement_end_date' => 'Partnership Agreement Effectivity End Date (DD/MM/YYYY)',
        'date_unexamined' => 'Date of Publication of Unexamined Application (DD/MM/YYYY)',
        'date_grantpatent' => 'Date of Grant of Patent (DD/MM/YYYY)',
    ],

    'publication_fields' => [
        'name_journal' => 'Name of Journal/Book/Conference Publication/Other Publication',
        'name_publisher' => 'Name of Publisher',
        'type_of_publisher' => 'Type of Publisher',
        'location_publisher' => 'Location of Publisher',
        'volume_issue_no' => 'Volume No. and Issue No.',
        'doi_url' => 'DOI or URL',
        'isbn_issn' => 'ISBN or ISSN',
        'web_science' => 'Web of Science (ISI)',
        'elsevier_scopus' => "Elsevier's Scopus",
        'elsevier_science_direct' => "Elsevier's ScienceDirect",
        'pub_med' => 'PubMed/MEDLINE',
        'ched_recognized_journal' => 'CHED Recognized Journal',
        'reputable_db' => 'Other Reputable Database',
        'journal_title' => 'Journal/Book Title',
        'publication_year' => 'Publication Year',
    ],

    'supporting_fields' => [
        'support_link' => 'Supporting Evidence/s',
        'support_link_pub' => 'Supporting Evidence(s) - Proof of Publication',
        'proof_of_Utilization' => 'Supporting Evidence(s) - Proof of Utilization',
        'support_utilization' => 'Supporting Evidence(s) (Proof of Utilization)',
    ],

    'location_fields' => [
        'location_organizer' => 'Location of Organizer',
        'full_address' => 'Venue, City and Country',
        'location_event' => 'Location of Event',
        'location_event_venue' => 'Event Venue, City and Country',
        'location_venue' => 'Venue, City/Municipality and Province',
    ],

    'numeric_fields' => [
        'cost' => 'Project Cost',
        'amount_for_institute' => 'Amount for the Institute',
        'no_of__citation' => 'Number of Citations',
        'no_hours' => 'Number of Hours Required to Complete',
        'total_trainee' => 'Total Number of Trainees/Persons Served',
        'sample_size' => 'Sample Size',
    ],

    'other_fields' => [
        'status' => 'Status',
        'awarded_by' => 'Awarded by',
        'scopework' => 'Scope of Work',
        'scope_of_work' => 'Scope of Work on the part of UP based on the Partnership Agreement',
        'tech_transfer' => 'Technology or Knowledge Transfer to target users',
        'remarks' => 'Remarks',
        'survey' => 'Satisfaction Survey (Number of Responses)',
        'notes' => 'Special Notes about the Schedule',
        'patent_type' => 'Type of Patent',
        'application_no' => 'Application Number',
        'registration_no' => 'Registration Number',
        'name_commercial_product' => 'Name of Commercial Product',
        'stake_holder_category' => 'Stakeholder Category',
        'type_agreement' => 'Type of Partnership Agreement',
        'beneficiary' => 'Target Beneficiary Group',
        'no_beneficiary' => 'Number of Beneficiaries',
        'training_courses' => 'Training Courses (non-degree and non-credit)',
    ],

];
