<?php
return [

    'proposal' => [
        'id'             => 'No.',
        'title'          => 'Title',
        'research_category'       => 'Research Category',
        'proj_lead'         => 'Project Leader (SN, FN MI.)',
        'proj_staff'          => 'Project Staff (SN, FN MI.)',
        'implementing_unit'=> 'Implementing Unit',
        'collaborators'  => 'Collaborators',
        'durations'      => 'Project Duration',
        'cost'           => 'Project Cost',
        'fund_agency'     => 'Funding Agency',
        'fund_type'       => 'Funding Type',
        'date_submitted'  => 'Date Submitted (DD/MM/YYYY)',
        'status'   => 'Status',
    ],

    'research' => [
        'id'              => 'No.',
        'delivery_unit'    => 'Delivery Unit',
        'contributing_unit'=> 'Contributing/Implementing Unit',
        'type_category'            => 'Type',
        'program'       => 'Program Title',
        'proj_title'       => 'Project Title',
        'status'          => 'Project Status',
        'banner'          => 'Banner Program',
        'agora'           => 'AGORA',
        'proj_lead'          => 'Project Leader (SN, FN, MI)',
        'proj_staff'           => 'Project Staff (SN, FN, MI)',
        'collaborators'   => 'Collaborators',
        'durations'       => 'Project Duration (in months)',
        'start_date'       => 'Start Date (DD/MM/YYYY)',
        'end_date'         => 'End Date (DD/MM/YYYY)',
        'cost'            => 'Project Cost',
        'fund_source'      => 'Fund Source',
        'fund_agency'      => 'Funding Agency',
        'fund_type'        => 'Funding Type',
        'support_link'        => 'Supporting Evidences',
    ],

    'publication' => [
        'id'                  => 'No.',
        'delivery_unit'         => 'Delivery Unit',
        'contributing_unit'    => 'Contributing Unit',
        'prog_title'=> 'Title of Research Program/Project/Work',
        'pub_title'    => 'Title of Publication',
        'pub_type'   => 'Type of Publication',
        'publication_author'          => 'Name of Author and Co-Authors',
        'date_published'       => 'Date Published or Accepted for Publication (DD/MM/YYYY)',
        'name_journal'         => 'Name of Journal/Book/Conference Publication/Other Publication',
        'name_publisher'       => 'Name of Publisher',
        'type_of_publisher'     => 'Type of Publisher',
        'location_publisher'   => 'Location of Publisher',
        'name_editor'          => 'Name of Editor/s',
        'volume_issue_no'     => 'Volume No. and Issue No.',
        'doi_url'              => 'DOI or URL',
        'isbn_issn'            => 'ISBN or ISSN',
        'web_science'          => 'Web of Science (ISI)',
        'elsevier_scopus'      => "Elsevier's Scopus",
        'elsevier_science_direct'=> "Elsevier's ScienceDirect",
        'pub_med'              => 'PubMed/MEDLINE',
        'ched_recognized_journal'    => 'CHED Recognized Journal',
        'reputable_db'         => 'Other Reputable Database',
        'support_link_pub'  => 'Supporting Evidence(s) - Proof of Publication',
        'no_of__citation'        => 'Number of Citations',
        'proof_of_Utilization'  => 'Supporting Evidence(s) - Proof of Utilization',
    ],

    'extension' => [
        'delivery_unit'         => 'Delivery Unit',
        'contributing_unit'     => 'Implementing Unit',
        'collaborators'        => 'Collaborators',
        'program'         => 'Program Title',
        'proj_title'                => 'Project Title',
        'status'               => 'Status',
        'banner'               => 'Banner Program',
        'agora'                => 'AGORA',
        'type_category'             => 'Extension Category',
        'proj_author'               => 'Project Leader (SN, FN, MI)',
        'proj_staff'                => 'Project Staff (SN, FN, MI)',
        'training_courses'      => 'Training Courses (non-degree and non-credit)',
        'technical_advisor'     => 'Technical/Advisory Service for external clients',
        'info_dissemenation'    => 'Information Dissemination/Communication through mass media',
        'consultancy'          => 'Consultancy for external clients',
        'community_outreach'    => 'Community Outreach',
        'technology_transfer'   => 'Technology or Knowledge Transfer to target users',
        'organizing'           => 'Organizing such as symposium, forum, exhibit, performance, conference',
        'academic'             => 'Academic Degree Programs of the Unit  beneficiary(s)',
        'scopework'            => 'Scope of Work',
        'duration_month'        => 'Project Duration (months)',
        'duration_days'         => 'Project Duration (in days)',
        'start_date'            => 'Start Date (DD/MM/YYYY)',
        'end_date'              => 'End Date (DD/MM/YYYY)',
        'beneficiary'          => 'Target Beneficiary Group',
        'no_beneficiary'    => 'Number of Target Beneficiary Groups/Persons Served',
        'fund_source'           => 'Fund Source (Majority Share)',
        'fund_type'             => 'Funding Type',
        'fund_agency'           => 'Funding Agency',
        'cost'                 => 'Project Cost',
        'support_link'      => 'Supporting Evidence/s',
        'remarks'              => 'Remarks',
    ],

    'ipagrants' => [
        'id'                  => 'No.',
        'proj_author'       => 'Name of Faculty (SN, FN, MI)',
        'proj_staff'             => 'Other Authors',
        'publication_year'     => 'Publication Year',
        'article_title'        => 'Article Title',
        'awarded_by'           => 'Awarded by',
        'journal_title'        => 'Journal/Book Title',
        'support_link'         => 'Link',
        'pub_type'     => 'Publication Type',
        'amount_for_institute'  => 'Amount for the Institute',
        'status'              => 'Status',
    ],

    'otherawards' => [
        'id'             => 'No.',
        'year_awarded'    => 'Year',
        'name_of_holder'   => 'Name of Holder',
        'department'     => 'Dept/ Ins.',
        'title'          => 'Title',
        'date_awarded'    => 'Date',
        'type_category'           => 'Type',
    ],

    'studentawards' => [
        'id'             => 'No.',
        'year_awarded'    => 'Year',
        'name_of_holder'   => 'Name of Holder',
        'title'          => 'Title',
        'date_awarded'    => 'Date',
        'type'           => 'Type',
    ],
    'presentation' => [
        'delivery_unit'            => 'Delivery Unit',
        'contributing_unit'       => 'Contributing Unit',
        'prog_title'   => 'Title of Research Program/Project/Work',
        'paper_title' => 'Title of Paper Presented',
        'presentation_type'     => 'Type of Presentation',
        'title_of_conference'      => 'Title of Conference',
        'name_organizer'          => 'Name of Organizer',
        'location_organizer'      => 'Location of Organizer',
        'full_address'                  => 'Venue, City and Country',
        'conf_start_date'        => 'Conference Start Date (DD/MM/YYYY)',
        'conf_end_date'          => 'Conference End Date (DD/MM/YYYY)',
        'date_presentation'       => 'Date of Presentation (DD/MM/YYYY)',
        'support_link'    => 'Supporting Evidence(s)',
    ],

    'patent' => [
        'delivery_unit'                => 'Delivery Unit',
        'contributing_unit'           => 'Contributing Unit',
        'prog_title'       => 'Title of Research Program/Project/Work',
        'patent_title'                => 'Title of Patent',
        'patent_type'                 => 'Type of Patent',
        'application_no'              => 'Application Number',
        'name_inventor'               => 'Name of Inventor(s)',
        'name_applicant'              => 'Name of Applicant/Owner(s)',
        'date_unexamined'             => 'Date of Publication of Unexamined Application (DD/MM/YYYY)',
        'date_grantpatent'            => 'Date of Grant of Patent (DD/MM/YYYY)',
        'registration_no'             => 'Registration Number',
        'name_commercial_product'      => 'Name of Commercial Product',
        'support_link'            => 'Supporting Evidence(s)',
        'utilization_output'  => 'Utilization of Research Output',
        'support_utilization' => 'Supporting Evidence(s)',
    ],

    'others' => [
        'delivery_unit'               => 'Delivery Unit',
        'contributing_unit'          => 'Contributing Unit',
        'prog_title'      => 'Title of Research Program/Project/Work',
        'output_title'               => 'Title of Output',
        'type_output'                => 'Type of Output',
        'type_public_event'           => 'Type of Public Event',
        'title_event'                => 'Title of Event',
        'name_organizer'             => 'Name of Organizer/Curator/Producer/Publisher',
        'location_event'             => 'Location of Event',
        'location_event_venue'                => 'Event Venue, City and Country',
        'event_start_date'                 => 'Event Start Date (DD/MM/YYYY)',
        'event_end_date'                  => 'Event End Date (DD/MM/YYYY)',
        'date_output'                => 'Date the Output was first shown or released to the public (DD/MM/YYYY)',
        'support_link'           => 'Supporting Evidence/s',
        'utilization_output'               => 'Utilization of Research Outputs',
        'support_utilization'=> 'Supporting Evidence/s (Proof of Utilization)',
    ],


    'trainings' => [
        'delivery_unit'         => 'Delivery Unit',
        'contributing_unit'    => 'Contributing Unit',
        'type_category'        => 'Type of Activity',
        'location_venue'               => 'Venue, City/Municipality and Province',
        'start_date'           => 'Start Date (DD/MM/YYYY)',
        'end_date'             => 'End Date (DD/MM/YYYY)',
        'notes'               => 'Special Notes about the Schedule',
        'no_hours'      => 'K8. Number of Hours Required to Complete the ing Course',
        'total_trainee'        => 'Total Number of ees/Persons Served',
        'fund_source'          => 'Fund Source (Majority Share)',
        'support_link'      => 'Supporting Evidence/s',
        'sample_size'          => 'Sample Size',
        'survey'              => 'Satisfaction Survey (Number of Responses)',
        'support_utilization'=> 'Supporting Evidence/s',
    ],

    'partnership' => [
        'delivery_unit'             => 'Delivery Unit',
        'contributing_unit'        => 'Contributing Unit',
        'partnership_type' => 'Type of Extension Activities under Partnership',
        'training_courses'         => 'Training Courses (non-degree and non-credit)',
        'tech_advisor_external'     => 'Technical/Advisory Service for external clients',
        'info_dissemination'       => 'Information Dissemination/Communication through mass media',
        'consultancy_external'     => 'Consultancy for external clients',
        'community_outreach'       => 'Community Outreach',
        'tech_transfer'            => 'Technology or Knowledge Transfer to target users',
        'organizing_sympetc'       => 'Organizing such as symposium, forum, exhibit, performance, conference',
        'scope_of_work'             => 'Scope of Work on the part of UP based on the Partnership Agreement',
        'partner_stakeholder'      => 'Name of Partner Stakeholder',
        'stake_holder_category'     => 'Stakeholder Category',
        'type_agreement'           => 'Type of Partnership Agreement',
        'Agreement_start_date'          => 'Partnership Agreement Effectivity Start Date (DD/MM/YYYY)',
        'Agreement_end_date'            => 'Partnership Agreement Effectivity End Date (DD/MM/YYYY)',
        'support_link'         => 'Supporting Evidence/s',
    ],
 ];