<?php

return [

    'proposal' => [
        'id',
        'title',
        'research_category',
        'proj_lead',
        'proj_staff',
        'implementing_unit',
        'collaborators',
        'durations',
        'cost',
        'fund_agency',
        'fund_type',
        'date_submitted',
        'status',
    ],

    'research' => [
        'id',
        'delivery_unit',
        'contributing_unit',
        'type_category',
        'program',
        'proj_title',
        'status',
        'banner',
        'agora',
        'proj_lead',
        'proj_staff',
        'collaborators',
        'durations',
        'start_date',
        'end_date',
        'cost',
        'fund_source',
        'fund_agency',
        'fund_type',
        'support_link',
    ],

    'publication' => [
        'id',
        'delivery_unit',
        'contributing_unit',
        'prog_title',
        'pub_title',
        'pub_type',
        'publication_author',
        'date_published',
        'name_journal',
        'name_publisher',
        'type_of_publisher',
        'location_publisher',
        'name_editor',
        'volume_issue_no',
        'doi_url',
        'isbn_issn',
        'web_science',
        'elsevier_scopus',
        'elsevier_science_direct',
        'pub_med',
        'ched_recognized_journal',
        'reputable_db',
        'support_link_pub',
        'no_of__citation',
        'proof_of_Utilization',
    ],

    'extension' => [
        'delivery_unit',
        'contributing_unit',
        'collaborators',
        'program',
        'proj_title',
        'status',
        'banner',
        'agora',
        'type_category',
        'proj_author',
        'proj_staff',
        'training_courses',
        'technical_advisor',
        'info_dissemenation',
        'consultancy',
        'community_outreach',
        'technology_transfer',
        'organizing',
        'academic',
        'scopework',
        'duration_month',
        'duration_days',
        'start_date',
        'end_date',
        'beneficiary',
        'no_beneficiary',
        'fund_source',
        'fund_type',
        'fund_agency',
        'cost',
        'support_link',
        'remarks',
    ],

    'ipagrants' => [
        'id',
        'proj_author',
        'proj_staff',
        'publication_year',
        'article_title',
        'awarded_by',
        'journal_title',
        'support_link',
        'pub_type',
        'amount_for_institute',
        'status',
    ],

    'otherawards' => [
        'id',
        'year_awarded',
        'name_of_holder',
        'department',
        'title',
        'date_awarded',
        'type_category',
    ],

    'studentawards' => [
        'id',
        'year_awarded',
        'name_of_holder',
        'title',
        'date_awarded',
        'type',
    ],

    'presentation' => [
        'delivery_unit',
        'contributing_unit',
        'prog_title',
        'paper_title',
        'presentation_type',
        'title_of_conference',
        'name_organizer',
        'location_organizer',
        'full_address',
        'conf_start_date',
        'conf_end_date',
        'date_presentation',
        'support_link',
    ],

    'patent' => [
        'delivery_unit',
        'contributing_unit',
        'prog_title',
        'patent_title',
        'patent_type',
        'application_no',
        'name_inventor',
        'name_applicant',
        'date_unexamined',
        'date_grantpatent',
        'registration_no',
        'name_commercial_product',
        'support_link',
        'utilization_output',
        'support_utilization',
    ],

    'others' => [
        'delivery_unit',
        'contributing_unit',
        'prog_title',
        'output_title',
        'type_output',
        'type_public_event',
        'title_event',
        'name_organizer',
        'location_event',
        'location_event_venue',
        'event_start_date',
        'event_end_date',
        'date_output',
        'support_link',
        'utilization_output',
        'support_utilization',
    ],

    'trainings' => [
        'delivery_unit',
        'contributing_unit',
        'type_category',
        'location_venue',
        'start_date',
        'end_date',
        'notes',
        'no_hours',
        'total_trainee',
        'fund_source',
        'support_link',
        'sample_size',
        'survey',
        'support_utilization',
    ],

    'partnership' => [
        'delivery_unit',
        'contributing_unit',
        'partnership_type',
        'training_courses',
        'tech_advisor_external',
        'info_dissemination',
        'consultancy_external',
        'community_outreach',
        'tech_transfer',
        'organizing_sympetc',
        'scope_of_work',
        'partner_stakeholder',
        'stake_holder_category',
        'type_agreement',
        'Agreement_start_date',
        'Agreement_end_date',
        'support_link',
    ],

];
